Update Resume
MajorTreble/WhateverJobYouChoose-Soen6011summer2023 pull request #86
Opened 2023-07-19 18:58 UTC by MajorTreble

Change display of resume
Update one line item at a time
Added html includes

Task #41

2023-07-19 20:16 UTC, SoroorAghamiri requested changes
I tried running the application, but clicking on Create Profile has errors. See the attached screenshot.
<img width="1440" alt="Screenshot 2023-07-19 at 4 15 50 PM" src="https://github.com/MajorTreble/WhateverJobYouChoose-Soen6011summer2023/assets/26331855/8384609b-4203-4b39-8c07-387bb4365d16">

2023-07-19 20:33 UTC, MajorTreble commented
> I tried running the application, but clicking on Create Profile has errors. See the attached screenshot. <img alt="Screenshot 2023-07-19 at 4 15 50 PM" width="1440" src="https://user-images.githubusercontent.com/26331855/254700732-8384609b-4203-4b39-8c07-387bb4365d16.png">

I renamed Users to User but you still have the old table in your db. Please drop all tables.

2023-07-19 20:59 UTC, SoroorAghamiri commented
> > I tried running the application, but clicking on Create Profile has errors. See the attached screenshot. <img alt="Screenshot 2023-07-19 at 4 15 50 PM" width="1440" src="https://user-images.githubusercontent.com/26331855/254700732-8384609b-4203-4b39-8c07-387bb4365d16.png">
> 
> I renamed Users to User but you still have the old table in your db. Please drop all tables.

I couldn't delete it. It says that Users has a foreign key in Resume.

2023-07-19 21:06 UTC, MajorTreble commented
> > > I tried running the application, but clicking on Create Profile has errors. See the attached screenshot. <img alt="Screenshot 2023-07-19 at 4 15 50 PM" width="1440" src="https://user-images.githubusercontent.com/26331855/254700732-8384609b-4203-4b39-8c07-387bb4365d16.png">
> > 
> > 
> > I renamed Users to User but you still have the old table in your db. Please drop all tables.
> 
> I couldn't delete it. It says that Users has a foreign key in Resume.

You need to delete in reverse order, most tables, then resume and then user

2023-07-19 21:13 UTC, SoroorAghamiri approved these changes

2023-07-20 03:38 UTC, sepehr9877 commented
> I tried running the application, but clicking on Create Profile has errors. See the attached screenshot. <img alt="Screenshot 2023-07-19 at 4 15 50 PM" width="1440" src="https://user-images.githubusercontent.com/26331855/254700732-8384609b-4203-4b39-8c07-387bb4365d16.png">

so you are getting the same error , go to mysql drop all of your tables and re-run the application it should work . this is mainly because of changing the name of Entity class and not updating the db

2023-07-20 17:16 UTC, sepehr9877 commented on src/main/resources/templates/profile_employer.html
> +
later we can use this th:replace to remove replication in our code specially for navbar

2023-07-20 17:17 UTC, sepehr9877 approved these changes

2023-07-20 17:17 UTC, merged